services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: landing-page:latest
    container_name: landing_page_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
