import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "LaunchPulse",
  description: "La plataforma definitiva para lanzar tu producto al mercado con máxima conversión, analíticas avanzadas y rendimiento extremo.",
  url: "https://launchpulse.app",
  ogImage: "https://launchpulse.app/og.png",
  navItems: [
    { label: "Características", href: "#features" },
    { label: "Cómo funciona", href: "#how-it-works" },
    { label: "Planes", href: "#pricing" },
    { label: "Opiniones", href: "#testimonials" },
    { label: "FAQ", href: "#faq" },
  ],
  features: [
    {
      id: "feature-1",
      title: "Despliegue Ultrarrápido",
      description: "Optimizado para Next.js con carga instantánea y puntajes perfectos en Core Web Vitals.",
      iconName: "Zap",
      badge: "Rendimiento",
    },
    {
      id: "feature-2",
      title: "Analíticas en Tiempo Real",
      description: "Visualiza el comportamiento de tus usuarios y eventos de conversión sin ralentizar tu web.",
      iconName: "BarChart3",
      badge: "Métricas",
    },
    {
      id: "feature-3",
      title: "Seguridad End-to-End",
      description: "Protección de datos cifrada, cumplimiento RGPD y protección DDoS integrada por defecto.",
      iconName: "ShieldCheck",
      badge: "Seguridad",
    },
    {
      id: "feature-4",
      title: "Automatización de Workflows",
      description: "Conecta formularios con tu CRM, email marketing y Webhooks en segundos.",
      iconName: "Workflow",
    },
    {
      id: "feature-5",
      title: "Optimizador SEO con IA",
      description: "Generación automática de etiquetas OpenGraph, sitemap estructurado y metadatos dinámicos.",
      iconName: "Sparkles",
      badge: "IA Powered",
    },
    {
      id: "feature-6",
      title: "Soporte Multi-Idioma",
      description: "Internacionalización nativa para adaptar tu landing page a cualquier mercado en el mundo.",
      iconName: "Globe",
    },
  ],
  steps: [
    {
      step: "01",
      title: "Personaliza tu estructura",
      description: "Ajusta la configuración centralizada en site.ts con la identidad de tu marca e información del producto.",
      iconName: "Sliders",
    },
    {
      step: "02",
      title: "Conecta tus servicios",
      description: "Integra fácilmente tus APIs de pago (Stripe), email marketing (Resend) y analíticas en pocos minutos.",
      iconName: "Layers",
    },
    {
      step: "03",
      title: "Lanza y escala",
      description: "Despliega en tu plataforma favorita (Vercel, Netlify, VPS) y empieza a captar clientes desde el primer día.",
      iconName: "Rocket",
    },
  ],
  pricing: [
    {
      id: "starter",
      name: "Starter",
      description: "Ideal para proyectos personales, MVPs y creadores independientes.",
      priceMonthly: 19,
      priceYearly: 15,
      features: [
        "1 proyecto activo",
        "Analíticas básicas",
        "Formularios ilimitados",
        "Soporte por comunidad",
        "Dominio personalizado",
      ],
      ctaText: "Empieza Gratis",
      ctaHref: "#signup",
    },
    {
      id: "pro",
      name: "Pro",
      description: "Para startups en crecimiento y equipos que necesitan maximizar conversiones.",
      priceMonthly: 49,
      priceYearly: 39,
      popular: true,
      features: [
        "Proyectos ilimitados",
        "Analíticas avanzadas en tiempo real",
        "Integración con CRM y Webhooks",
        "Optimizador SEO con IA",
        "Soporte prioritario 24/7",
        "A/B Testing en componentes",
      ],
      ctaText: "Prueba 14 días gratis",
      ctaHref: "#signup",
    },
    {
      id: "enterprise",
      name: "Enterprise",
      description: "Para grandes empresas con requisitos a medida, SLA y seguridad dedicada.",
      priceMonthly: 149,
      priceYearly: 119,
      features: [
        "Todo lo incluido en Pro",
        "SLA garantizado de 99.9%",
        "Infraestructura dedicada",
        "Gestor de cuenta exclusivo",
        "Auditoría de seguridad personalizada",
        "Integraciones a medida",
      ],
      ctaText: "Contactar Ventas",
      ctaHref: "#contact",
    },
  ],
  testimonials: [
    {
      id: "1",
      quote: "Gracias a esta estructura pudimos validar nuestra startup y conseguir más de 1,200 leads en la primera semana. La velocidad es impresionante.",
      author: "Carlos Mendoza",
      role: "Fundador & CEO",
      company: "TechFlow",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150",
      rating: 5,
    },
    {
      id: "2",
      quote: "La organización de componentes en Next.js con Tailwind y pnpm nos ahorró semanas de desarrollo. Es limpia, escalable y muy fácil de mantener.",
      author: "Laura Fernández",
      role: "Lead Frontend Engineer",
      company: "ScaleStudio",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150",
      rating: 5,
    },
    {
      id: "3",
      quote: "El diseño es limpio, moderno y la tasa de conversión aumentó un 35% respecto a nuestra landing page anterior.",
      author: "Marcos Ruiz",
      role: "Head of Growth",
      company: "NextGen Media",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150",
      rating: 5,
    },
  ],
  faqs: [
    {
      id: "faq-1",
      question: "¿Por qué utilizar Next.js con App Router y Tailwind CSS?",
      answer: "Next.js proporciona Renderizado en el Servidor (SSR) y Generación Estática (SSG) para un rendimiento SEO inigualable. Tailwind CSS permite diseñar componentes responsivos e interactivos con rapidez sin archivos CSS pesados.",
    },
    {
      id: "faq-2",
      question: "¿Puedo personalizar los colores y estilos fácilmente?",
      answer: "¡Absolutamente! Todos los colores, tipografías y efectos están centralizados mediante variables CSS y clases de Tailwind. Solo edita globals.css o site.ts para ajustar la marca.",
    },
    {
      id: "faq-3",
      question: "¿Qué ventajas tiene usar pnpm como gestor de paquetes?",
      answer: "pnpm ahorra gigabytes de espacio en disco usando un almacén de contenido direccionable, y realiza instalaciones hasta 2x más rápidas que npm o yarn.",
    },
    {
      id: "faq-4",
      question: "¿Cómo se gestionan las interacciones y los estados en los formularios?",
      answer: "Los componentes interactivos (como el menú móvil, toggle de precios o acordión de preguntas) utilizan componentes cliente ('use client') manteniendo el resto como Server Components para máximo rendimiento.",
    },
    {
      id: "faq-5",
      question: "¿Se puede desplegar en Vercel u otros proveedores fácilmente?",
      answer: "Sí, la estructura es 100% estándar de Next.js. Puedes desplegar en Vercel con solo conectar tu repositorio de Git en 1 clic.",
    },
  ],
  socials: [
    { platform: "Twitter", href: "https://twitter.com", iconName: "Twitter" },
    { platform: "GitHub", href: "https://github.com", iconName: "Github" },
    { platform: "LinkedIn", href: "https://linkedin.com", iconName: "Linkedin" },
  ],
};
